spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security_ok
    username: postgres
    password: al5gtuv*
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: cristinapichiu38@gmail.com
    password: jgjqfkhodubtmsjd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

google:
  cloud:
    storage:
      bucket: bucket_documents_1
      profile-bucket: pictures_bucket_skillmap # Adaugă acest rând
    credentials:
      file:
        path: "C:/Users/Hp/Desktop/skillmap-427011-aa71d766d569.json"

